# This workflow will build a Java project with Mav
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven  

name: JBoss EAP OpenShift Modules - Bats
on:
  push:
    branches: [ master ]
  pull_request:
     branches: [ master ]
env:
  LANG: en_US.UTF-8

jobs:
  bats:
    name: Bats Shell Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: sudo apt-get install bats
    - name: Run Bats
      shell: bash
      run: |
          rc=0
          echo "TAP version 13"
          for testName in `find ./ -name *.bats`; 
          do 
            echo ${testName}; 
            bats --tap ${testName} || rc=$?
          done
          exit ${rc}
